### PR TITLE
Update to support newer servant and add API call

### PR DESCRIPTION
**Pull request by greenrd**

### CODE REVIEW

**Comment by markus1189** [comment]
First of all thanks for contributing ;)

Unfortunately, this seems to also break other stuff, for example the `week` command now gives "Old api is deprecated".  Seems like we have to fix that as well because we can merge this.

**Comment by greenrd** [comment]
Oops, should be fixed now. I can rebase before you merge, to annihilate my mistaken change.

**Comment by markus1189** [comment]
No need I'll handle it after testing it again tomorrow, thanks!

**Comment by markus1189** [comment]
Merged in 3fc4805b7cd97c4ed9122549006f31e7f5867311, thanks!

**Pull request closed without merging**
